IMAGE gfx_palette0 				"gfx/palette0.png" 				0
IMAGE gfx_palette1 				"gfx/palette1.png" 				0
IMAGE gfx_battle_enemies 		"gfx/battle_enemies.png" 		0
IMAGE gfx_battle_enemies_leshy	"gfx/battle_enemies_leshy.png"	0
IMAGE gfx_battle_player 		"gfx/battle_player.png" 		0
IMAGE gfx_border 				"gfx/border.png" 				0
IMAGE gfx_font 					"gfx/font.png" 					0
IMAGE gfx_koschey 				"gfx/koschey.png" 				0
IMAGE gfx_logo_big 				"gfx/logo_big.png" 				0
IMAGE gfx_logo_small 			"gfx/logo_small.png" 			0
IMAGE gfx_splash 				"gfx/splash.png" 				0
IMAGE gfx_stats_inventory 		"gfx/stats_inventory.png" 		0
IMAGE gfx_stats_items 			"gfx/stats_items.png" 			0
IMAGE gfx_stats_village 		"gfx/stats_village.png" 		0