WAV sfx_music_intro 	"sfx/music_intro.wav" 	XGM
WAV sfx_music_boss 		"sfx/music_boss.wav" 	XGM
WAV sfx_music_over 		"sfx/music_over.wav" 	XGM
WAV sfx_sound_type_0 	"sfx/sound_type_0.wav" 	XGM
WAV sfx_sound_type_1 	"sfx/sound_type_1.wav" 	XGM
WAV sfx_sound_type_2 	"sfx/sound_type_2.wav" 	XGM
WAV sfx_sound_type_3 	"sfx/sound_type_3.wav" 	XGM
WAV sfx_sound_type_4 	"sfx/sound_type_4.wav" 	XGM
WAV sfx_sound_type_5 	"sfx/sound_type_5.wav" 	XGM
WAV sfx_sound_type_6 	"sfx/sound_type_6.wav" 	XGM
WAV sfx_sound_type_7 	"sfx/sound_type_7.wav" 	XGM
WAV sfx_sound_type_8 	"sfx/sound_type_8.wav" 	XGM
WAV sfx_sound_type_9 	"sfx/sound_type_9.wav" 	XGM
WAV sfx_sound_type_10 	"sfx/sound_type_10.wav" XGM
WAV sfx_sound_type_11	"sfx/sound_type_11.wav" XGM
WAV sfx_sound_type_12 	"sfx/sound_type_12.wav" XGM
WAV sfx_sound_type_13 	"sfx/sound_type_13.wav" XGM